# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_pic',
            field=models.ImageField(default=None, upload_to='profile/background'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='profile/profile'),
        ),
        migrations.AlterField(
            model_name='wallposts',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wallposts',
            name='post',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='wallposts',
            name='videos',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
    ]
